version: '3.7'
services:
  mysql:
    container_name: "mysql"
    image: mysql:debian
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  api:
    container_name: "cat-api"
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: "${MYSQL_PORT}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  nginx:
    container_name: "nginx"
    image: nginx:latest
    restart: always
    ports:
      - "60080:80"
    volumes:
      - ./web/:/usr/share/nginx/html/api
volumes:
  web: